name: CI - Pipeline

on:
  workflow_dispatch: {}
  push:
    branches:
    - master
    
jobs:
  Smoke-Tests:
    timeout-minutes: 5
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - uses: actions/setup-node@v4
      with:
        node-version: 12.22.12

    - name: Check Node
      run: node --version

    - name: set environment
      run: cp .env.template .env

    - name: Start containers
      run: docker-compose up --detach

    - name: Wait a little
      run: sleep 10

    - name: Setup dev
      run: npm run setup:dev

    - name: start backend
      run: npm run start:dev &

    - name: start frontend
      run: BROWSER=none npm run start:public &

    - name: Wait a little
      run: sleep 10

    - name: Database Cleanup
      run: npm run db:delete:dev && npm run db:create:dev && npm run migrate:dev

    - name: Smoke-Tests
      run: |
        chmod +x src/smoke_test/smoke-test.sh
        ./src/smoke_test/smoke-test.sh
    
    - name: Database Cleanup
      run: npm run db:delete:dev && npm run db:create:dev && npm run migrate:dev

    - uses: matt-ball/newman-action@master
      with:
        collection: ./src/smoke_test/DDDForum.postman_collection.json
        delayRequest: 400

      
    - name: Wait a little
      run: sleep 10

  Regression-Tests:
    timeout-minutes: 25
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - uses: actions/setup-node@v4
      with:
        node-version: 12.22.12

    - name: Check Node
      run: node --version

    - name: set environment
      run: cp .env.template .env

    - name: Start containers
      run: docker-compose up --detach

    - name: Wait a little
      run: sleep 10

    - name: Setup dev
      run: npm run setup:dev

    - name: start backend
      run: npm run start:dev &

    - name: start frontend
      run: BROWSER=none npm run start:public &

    - name: Wait a little
      run: sleep 10

    - name: Database Cleanup
      run: npm run db:delete:dev && npm run db:create:dev && npm run migrate:dev

    - name: Regression Tests
      run: npm run test:api:regression