@startuml SD-MyCommentedPosts
autonumber 

actor User
participant Routes
participant "getPostsWithMyCommentsController: GetPostsWithMyCommentsController" as getPostsWithMyCommentsController
participant "useCase: GetPostsWithMyComments " as GetPostsWithMyCommentsUseCase
participant "postRepo: IPostRepo" as IPostRepo
database MySQL as database

User -> Routes: call endpoint (method: "GET", route: "/mycomments")
    activate Routes
    Routes -> getPostsWithMyCommentsController: execute(req, res) 
    activate getPostsWithMyCommentsController
        getPostsWithMyCommentsController -> getPostsWithMyCommentsController: executeImpl(req, res)
        getPostsWithMyCommentsController -> GetPostsWithMyCommentsUseCase: execute(dto)
        activate GetPostsWithMyCommentsUseCase
             GetPostsWithMyCommentsUseCase-> IPostRepo: getPostsWithMyComments(member)
            activate IPostRepo
                IPostRepo -> database: this.models.sequelize.query("...")
                activate database
                    database -> IPostRepo: string[]
                deactivate database
                IPostRepo -> database: PostModel.findAll(detailsQuery)
                activate database
                    database -> IPostRepo: PostDetails[]
                deactivate database
                IPostRepo -> GetPostsWithMyCommentsUseCase: PostDetails[] 
            deactivate IPostRepo

            GetPostsWithMyCommentsUseCase -> getPostsWithMyCommentsController: Result.ok<PostDetails[]>(posts)
            deactivate GetPostsWithMyCommentsUseCase

        getPostsWithMyCommentsController -> Routes: this.ok<GetPostsWithMyCommentsResponseDTO>(res, ...);
        deactivate getPostsWithMyCommentsController
        Routes -> User
    deactivate Routes
@enduml

