@startuml US030
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Visualization of my comments - User

autonumber

actor "User" as User
participant "System" as System

activate User
    User -> System: Access the DDD forum
   
    activate System
        System --> User : Return the default page 
    deactivate System

    User -> System : Access on the "my comments" options

    activate System
        System --> User : Return the posts that have comments made by the member
    deactivate System

@enduml