@startuml SD-US019

title US019 SD - Get Percentage of Posts without Comments on a Given Day

actor Users
participant Routes
participant "Get Percentage Controller" as Controller
participant "Get Percentage Service" as Service
participant "Post Repository" as Repo
database MySQL as Database

Users -> Routes: 1. Call Endpoint (method: Get, route: "/PercentageOfPostsWithoutComments", header: "Authorization")
activate Routes

Routes -> Controller: 2. .execute(req, res)
activate Controller

Controller -> Service: 3. .executeImpl(req: DecodedExpressRequest, res: express.Response)
activate Service

Service -> Repo: 4. GetPercentageOfPostsWithoutComments(date?: Date | string)
activate Repo

Repo -> Database: 5. .getTotalNumberOfPosts()
activate Database
Database --> Repo: 
deactivate Database
Repo --> Service: 7. GetPercentageOfPostsWithoutComments(number)
deactivate Repo

Service --> Controller: 8. percentage(number)

Controller --> Routes: 9. res.send(percentage(number))

Routes --> Users: 10. Response

deactivate Controller
deactivate Service
deactivate Routes

@enduml
