@startuml US013v-SSD

title Sequence diagram US013v-SSD (Visitor delete user (Username))

actor Visitor
boundary System



Visitor -> System: 1. Visits Website
activate Visitor
System  --> Visitor: 2. Error message "No usernames available"
deactivate System
deactivate Visitor

@enduml

