@startuml SD-getUsernamesWhithoutPostsAndComments

title US013 SD - get Usernames Without Posts And Comments (helper function)

actor Users
participant Routes
participant "getUsernamesWhithoutPostsAndCommentsController: getUsernamesWhithoutPostsAndCommentsController" as getUsernamesWhithoutPostsAndCommentsController
participant "useCase: getUsernamesWhithoutPostsAndCommentsUseCase" as getUsernamesWhithoutPostsAndCommentsUseCase
participant "postRepo: IPostRepo" as IPostRepo
participant "Post: Post" as Post
database MySQL as database

Users -> Routes: call Endpoint (method: Post, route: "/getUsernamesWhithoutPostsAndComments", header: "Authorization")
activate Routes

Routes -> getUsernamesWhithoutPostsAndCommentsController: .execute(req, res)
activate getUsernamesWhithoutPostsAndCommentsController

getUsernamesWhithoutPostsAndCommentsController -> getUsernamesWhithoutPostsAndCommentsController: .executeImpl(req: DecodedExpressRequest, res: express.Response)
getUsernamesWhithoutPostsAndCommentsController -> getUsernamesWhithoutPostsAndCommentsUseCase: .execute(dto)
activate getUsernamesWhithoutPostsAndCommentsUseCase

getUsernamesWhithoutPostsAndCommentsUseCase -> IPostRepo: .getUsernamesWhithoutPostsAndComments() : string[]
activate IPostRepo

IPostRepo -> Post: .getUsernamesWhithoutPostsAndComments() : string[]
activate Post

Post -> database: .post(string[])
activate database

database --> Post: getUsernamesWhithoutPostsAndComments
deactivate database

Post --> IPostRepo: getUsernamesWhithoutPostsAndComments : string[]
deactivate Post

IPostRepo --> getUsernamesWhithoutPostsAndCommentsUseCase: .getUsernamesWhithoutPostsAndComments() : string[]
deactivate IPostRepo

getUsernamesWhithoutPostsAndCommentsUseCase --> getUsernamesWhithoutPostsAndCommentsController: list of usernames
deactivate getUsernamesWhithoutPostsAndCommentsUseCase

getUsernamesWhithoutPostsAndCommentsController --> Routes: list of usernames
deactivate getUsernamesWhithoutPostsAndCommentsController

Routes --> Users: list of usernames
deactivate Routes

@enduml


