@startuml US013-SSD

title Sequence diagram US013-SSD (Member delete user (Username))

actor Member
boundary System

Member -> System: 1. Clicks on the member page
activate Member
activate System 
System --> System: Check conditions for deletion (not exist username)
System --> Member: 2. Error message "No usernames available"


deactivate System
deactivate Member

@enduml