@startuml US009-SSDa
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Vote on Post (as a visitor)

autonumber

actor "Visitor" as User


participant "System" as System

activate User

    User -> System : asks to see a post on the forum
    activate System

        System --> User : present the selected post or a list of posts
    deactivate System

    User -> System : wants to vote a post
    activate System

        System --> User : display a message requiring to log in or create an account
    deactivate System

deactivate User


@enduml