@startuml SD-US020

title US020 SD - Get Hour With the Most Posts Created In a Day

actor Users
participant Routes
participant "GetHourWithMostPostsController: GetHourWithMostPostsController" as GetHourWithMostPostsController
participant "GetHourWithMostPostsUseCase: GetHourWithMostPostsUseCase" as GetHourWithMostPostsUseCase
participant "PostRepo: PostRepo" as PostRepo
database MySQL as Database

Users -> Routes: 1. Call Endpoint (method: Get, route: "/", header: "Authorization")
activate Routes

Routes -> GetHourWithMostPostsController: 2. .execute(req, res)
activate GetHourWithMostPostsController

GetHourWithMostPostsController -> GetHourWithMostPostsController: 3. .executeImpl(req: DecodedExpressRequest, res: express.Response)
GetHourWithMostPostsController -> GetHourWithMostPostsUseCase: 4. .execute(dto)
activate GetHourWithMostPostsUseCase

GetHourWithMostPostsUseCase -> PostRepo: 5. .getHourWithMostPostsCreatedInaDay(day: Date)
activate PostRepo

PostRepo -> Database: 6. .getHourWithMostPostsCreatedInaDay(day: Date)
activate Database
Database --> PostRepo: 7. hourWithMostPosts(number)
deactivate Database
PostRepo --> GetHourWithMostPostsUseCase: 7. hourWithMostPosts(number)
deactivate PostRepo

GetHourWithMostPostsUseCase --> GetHourWithMostPostsController: 8. hourWithMostPosts(number)

GetHourWithMostPostsController --> Routes: 9. res.send(hourWithMostPosts(number))

Routes --> Users: 10. Response

deactivate GetHourWithMostPostsController
deactivate GetHourWithMostPostsUseCase
deactivate Routes

@enduml

