@startuml SD-Display post with most Comments on a given day

title US016 SD - Display post with most Comments on a given day

actor Users
participant Routes
participant "getPostsByDateController:getPostsByDateController" as getPostsByDateController
participant "useCase: GetPostsByDate" as GetPostsByDateUseCase
participant "postRepo: IPostRepo" as IPostRepo
database MySQL as database

Users -> Routes : call Endpoint (method: GET, route: "/", header: "specificDay")
activate Routes

Routes -> getPostsByDateController: .execute(req, res)
activate getPostsByDateController

getPostsByDateController -> getPostsByDateController: .executeImpl(req: DecodedExpressRequest,res: express.Response)
getPostsByDateController -> GetPostsByDateUseCase: .execute(dto)
activate GetPostsByDateUseCase

GetPostsByDateUseCase -> IPostRepo: .getPostsByDate (date: string)
activate IPostRepo

IPostRepo -> database: getPostsByDate(date?: Date | string)
activate database

database --> IPostRepo: <PostDetails[]>(posts)
deactivate database

IPostRepo --> GetPostsByDateUseCase: <PostDetails[]>(posts)
deactivate IPostRepo
deactivate GetPostsByDateUseCase
deactivate getPostsByDateController
deactivate Routes

@enduml
