@startuml US027
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Visualization of the Popular posts - User

autonumber

actor "User" as User
participant "System" as System

activate User
    User -> System: Access the DDD forum
   
    activate System
        System --> User : Return the default page 
    deactivate System

    User -> System : Access on the "Popular" posts options

    activate System
        System --> User : Return the  top "Popular" posts  
    deactivate System

    User -> System : Access the "Please comment me"

    activate System 
        System --> User : Return the post comment page
    deactivate System

@enduml