@startuml US005e-SSD
title SSD - US018 - View Members without any activity (Posts and Comments) for a Specific Day
autonumber 

actor User
participant Routes
participant "getListOfUsernamesWithoutPostsAndWithoutCommentsByDateController: GetListOfUsernamesWithoutPostsAndWithoutCommentsByDateController" as GetListOfUsernamesWithoutPostsAndWithoutCommentsByDateController
participant "useCase: GetListOfUsernamesWithoutPostsAndWithoutCommentsByDate " as GetListOfUsernamesWithoutPostsAndWithoutCommentsByDateUseCase
participant "postRepo: IPostRepo" as IPostRepo
database MySQL as database

User -> Routes: call endpoint (method: "GET", route: "/getListOfUsernamesWithoutPostsAndWithoutCommentsByDate")
    activate Routes
    Routes -> GetListOfUsernamesWithoutPostsAndWithoutCommentsByDateController: execute(req, res) 
    activate GetListOfUsernamesWithoutPostsAndWithoutCommentsByDateController
        GetListOfUsernamesWithoutPostsAndWithoutCommentsByDateController -> GetListOfUsernamesWithoutPostsAndWithoutCommentsByDateController: executeImpl(req, res)
        GetListOfUsernamesWithoutPostsAndWithoutCommentsByDateController -> GetListOfUsernamesWithoutPostsAndWithoutCommentsByDateUseCase: execute(dto)
        activate GetListOfUsernamesWithoutPostsAndWithoutCommentsByDateUseCase
             GetListOfUsernamesWithoutPostsAndWithoutCommentsByDateUseCase-> IPostRepo: getListOfUsernamesWithoutPostsAndWithoutCommentsByDate()
            activate IPostRepo
                IPostRepo -> database: PostModel.sequelize.query()
                activate database
                    database -> IPostRepo: string[]
                deactivate database
                IPostRepo -> GetListOfUsernamesWithoutPostsAndWithoutCommentsByDateUseCase: string[] 
            deactivate IPostRepo

            GetListOfUsernamesWithoutPostsAndWithoutCommentsByDateUseCase -> GetListOfUsernamesWithoutPostsAndWithoutCommentsByDateController:  Result.ok<string[]>(usernames)
            deactivate GetListOfUsernamesWithoutPostsAndWithoutCommentsByDateUseCase

        GetListOfUsernamesWithoutPostsAndWithoutCommentsByDateController -> Routes:  this.ok<GetListOfUsernamesWithoutPostsAndWithoutCommentsByDateDTO>(res, ...);
        deactivate GetListOfUsernamesWithoutPostsAndWithoutCommentsByDateController
        Routes -> User: 200 OK
    deactivate Routes

@enduml