@startuml US023
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - US023 SSD-  Highlight in yellow background posts between 1/3 and 2/3 of the comments of the highest commented

autonumber

actor "User" as User
boundary System

activate User
    User -> System: Access DDD forum
   
  
    activate System
        System --> User : Return the default page 
    deactivate System

    User -> System : Access "Ascending" page

    activate System
    System --> User: Highlights in yellow the posts between 1/3 and 2/3 of the comments of the highest commented
    deactivate System

@enduml
