name: Release - Pipeline

on:
  workflow_dispatch: {}
  release:
    branches:
    - master
    
jobs:
  docker:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - uses: actions/setup-node@v4
      with:
        node-version: 12.22.12

    - name: Check Node
      run: node --version

    - name: set environment
      run: cp .env.template .env

    - name: Start containers
      run: docker-compose up --detach

    - name: Wait a little
      run: sleep 10

    - name: Setup dev
      run: npm run setup:dev

    - name: start backend
      run: npm run start:dev &

    - name: start frontend
      run: BROWSER=none npm run start:public &

    - name: Wait a little
      run: sleep 10

    - name: DB Loading - Test Environment Setup
      run: npm run db:seednonfunc:dev
  
    - uses: actions/checkout@v2

    - name: Run JMeter Action on a test
      uses: rbhadti94/apache-jmeter-action@v0.5.0
      with:
          testFilePath: src/non_func_test/Test-Plan-DDD-Forum-Group-3.jmx
          outputReportsFolder: reports/
          args: "--loglevel INFO"