@startuml US10C-SSD
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Vote on Comment  - Member

autonumber


actor "Member" as User
participant "System" as System

activate User


    User -> System : choose a post that has comments
    activate System

        System --> User : Show selected post
    deactivate System

    User -> System : press up vote button on a comment 
    activate System

    System --> User : Show up vote increment on the comment
    deactivate System
@enduml